### ISSUE TITLE
0.2.12 broken on macOS 10.14

### ISSUE THREAD

**Issue by keith** [google/xctestrunner#18]
The 0.2.12 par file upload to the releases uses this shebang:

```
#!/usr/bin/env python2
```

Which doesn't exist on macOS before Catalina. Instead it should be `/usr/bin/python2.7` or `/usr/bin/env python2.7`

**Comment by gyfelton** [comment]
Encounter the same problem on our CI machines

**Comment by segiddins** [comment]
cc @albertdai

**Comment by albertdai** [comment]
Sorry for breaking your sides. I did not test it out in macOS 10.14.

I did not do change for the python 2 specific. I guess it may be done by bazel which I built the par binary. I will take a look at that.

**Comment by albertdai** [comment]
@segiddins You could follow the "installation" guidance in the README to build the par binary with your local bazel.

**Comment by albertdai** [comment]
With local debugging, found the it was broke by https://github.com/google/xctestrunner/commit/03831a9d9b20adea7810483259b44c5fde10e919.

I sent another CL to revert this change. I will try to do another release.

**Comment by keith** [comment]
@albertdai I don't see how that commit is related, if you build master now it embeds a shebang for python3, which xctestrunner isn't compatible with:

```
% head -1 bazel-bin/xctestrunner/ios_test_runner.par
#!/usr/bin/env python3
% bazel-bin/xctestrunner/ios_test_runner.par
Traceback (most recent call last):
  File "/Users/ksmiley/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/ksmiley/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "bazel-bin/xctestrunner/ios_test_runner.par/__main__.py", line 329, in <module>
  File "bazel-bin/xctestrunner/ios_test_runner.par/__main__.py", line 323, in main
AttributeError: 'Namespace' object has no attribute 'func'
```

I've submitted a PR to subpar to allow overriding the shebang, so that we could provide `/usr/bin/python2.7` directly https://github.com/google/subpar/pull/125

**Comment by keith** [comment]
I've submitted a fix for this https://github.com/google/xctestrunner/pull/20

**Comment by albertdai** [comment]
Thanks Keith and sorry for the late response on the release.

I have added the new release 0.2.13 in this repo and bazel side: https://github.com/bazelbuild/rules_apple/blob/master/apple/repositories.bzl

**Comment by keith** [comment]
Thanks!
